var data=[
    {
      "id": 1,
      "parentId": 1,
      'level': 0,
      "name": "patient",
      'relationID': 0,
    },
    {
      "id": 2,
      "parentId": 1,
      "name": "patient's partner",
      'level': 0,
      'relationID': 1,
    },
    {
      "id": 3,
      "parentId": 1,
      "name": "patient's child1",
      'level': 1,
      'relationID': 2,
    },
    {
      "id": 4,
      "parentId": 1,
      "name": "Patient's child2",
      'level': 1,
      'relationID': 2,
    },
    {
      "id": 5,
      "parentId": 1,
      'level': -1,
      "name": "Patient's parent1",
      'relationID': 3,
    },
    {
      "id": 6,
      "parentId": 1,
      'level': -1,
      "name": "Patient's parent2",
      'relationID': 3,
    },
    {
      "id": 7,
      "parentId": 2,
      "name": "Partner's Parent1",
      'level': -1,
      'relationID': 3,
    },
    {
      "id": 8,
      "parentId": 2,
      "name": "Partner's parent2",
      'level': -1,
      'relationID': 3,
    },
    {
      "id": 9,
      "parentId": 5,
      "name": "Patient's grand parent1",
      'level': -1,
      'relationID': 3,
    },
    {
      "id": 10,
      "parentId": 5,
      "name": "Patient's grand parent2",
      'level': -1,
      'relationID': 3,
    },
    
  ];